"""
CarbonChain - Evidence & Provenance Models

This module defines the data contracts for the evidence system that underpins
AI MRV verification, authority review, community review, and minting trust.

DESIGN PRINCIPLES:
1. IMMUTABILITY: Once created, evidence records cannot be modified or deleted.
   This ensures auditability and prevents tampering with the verification chain.

2. TRANSPARENCY: Every evidence record includes a SHA256 hash of its immutable
   fields, enabling public verification of data integrity.

3. TRACEABILITY: Evidence records are linked to claims and include source
   attribution, allowing stakeholders to trace the provenance of all data.

4. HASHABILITY: The hash serves as a cryptographic fingerprint that can be
   used to verify evidence integrity without exposing sensitive data.

WHY IMMUTABILITY MATTERS:
- Carbon credit markets require trust in verification data
- Regulators need audit trails that cannot be retroactively altered
- Community oversight depends on transparent, tamper-evident records
- Future blockchain integration requires deterministic hashing
"""

import hashlib
from datetime import datetime
from enum import Enum
from typing import Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, Field, model_validator


class EvidenceType(str, Enum):
    """
    Classification of evidence sources in the verification chain.

    SYSTEM_AI: Automatically generated by AI/ML systems (e.g., satellite MRV)
    USER_UPLOAD: Submitted by claimants (photos, documents)
    DOCUMENT: Official documents, reports, certifications
    COMMUNITY_REPORT: Observations submitted by community reviewers
    """

    SYSTEM_AI = "system_ai"
    USER_UPLOAD = "user_upload"
    DOCUMENT = "document"
    COMMUNITY_REPORT = "community_report"


class EvidenceSource(str, Enum):
    """
    Attribution of who provided the evidence.

    Enables filtering and trust assessment based on source.
    """

    SYSTEM = "system"  # Generated by CarbonChain platform
    AUTHORITY = "authority"  # Submitted by government/regulator
    COMMUNITY = "community"  # Submitted by NGO/public observer
    USER = "user"  # Submitted by claimant


class EvidenceSubmission(BaseModel):
    """
    Input model for creating new evidence.

    Does not include system-generated fields like ID, hash, or timestamp.
    """

    claim_id: UUID = Field(..., description="ID of the claim this evidence supports")
    type: EvidenceType = Field(..., description="Classification of evidence type")
    source: str = Field(
        ...,
        description="Attribution of evidence source (system, authority, community, user)",
    )
    title: str = Field(
        ...,
        min_length=3,
        max_length=200,
        description="Short descriptive title for the evidence",
    )
    description: str = Field(
        ...,
        min_length=10,
        max_length=10000,
        description="Detailed description of what this evidence shows",
    )
    data_ref: str = Field(
        ...,
        max_length=1000,
        description="Reference to evidence data (URL, file path, or logical reference)",
    )
    confidence_weight: float = Field(
        default=0.5,
        ge=0.0,
        le=1.0,
        description=(
            "Trust weight for evidence aggregation (0.0-1.0). "
            "This represents the weight given to this evidence when aggregating multiple evidence sources, "
            "not verification confidence or AI consistency confidence."
        ),
    )


class Evidence(EvidenceSubmission):
    """
    Complete evidence record including system-generated fields.

    IMMUTABILITY CONTRACT:
    Once created, Evidence records MUST NOT be modified or deleted.
    The hash field provides cryptographic proof of data integrity.
    Any attempt to modify evidence should create a new record instead.

    HASH COMPUTATION:
    The hash is a SHA256 digest of the following fields (in order):
    - claim_id
    - type
    - source
    - data_ref
    - created_at (ISO format)

    This hash can be independently verified by any party to ensure
    the evidence has not been tampered with.
    """

    id: UUID = Field(
        default_factory=uuid4, description="Unique identifier for this evidence record"
    )
    hash: str = Field(
        default="",
        description="SHA256 hash of immutable fields for integrity verification",
    )
    created_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="Timestamp when the evidence was recorded (immutable)",
    )

    @model_validator(mode="after")
    def compute_hash(self) -> "Evidence":
        """
        Compute SHA256 hash of immutable fields.

        This hash serves as a cryptographic fingerprint that:
        1. Proves the evidence has not been modified
        2. Enables public verification without exposing raw data
        3. Supports future blockchain anchoring
        """
        if not self.hash:  # Only compute if not already set
            hash_input = (
                f"{self.claim_id}|"
                f"{self.type.value}|"
                f"{self.source}|"
                f"{self.data_ref}|"
                f"{self.created_at.isoformat()}"
            )
            self.hash = hashlib.sha256(hash_input.encode("utf-8")).hexdigest()
        return self

    def verify_hash(self) -> bool:
        """
        Verify that the stored hash matches the computed hash.

        Returns:
            True if hash is valid, False if evidence may have been tampered with.
        """
        hash_input = (
            f"{self.claim_id}|"
            f"{self.type.value}|"
            f"{self.source}|"
            f"{self.data_ref}|"
            f"{self.created_at.isoformat()}"
        )
        expected_hash = hashlib.sha256(hash_input.encode("utf-8")).hexdigest()
        return self.hash == expected_hash

    class Config:
        """Pydantic configuration for the Evidence model."""

        json_schema_extra = {
            "example": {
                "claim_id": "550e8400-e29b-41d4-a716-446655440000",
                "type": "system_ai",
                "source": "system",
                "title": "Satellite-based MRV (Sentinel-2)",
                "description": "NDVI analysis from 2022-01-01 to 2024-12-31. Baseline NDVI: 0.45, Monitoring NDVI: 0.62, Delta: +0.17. Estimated CO₂e: 120-180 tonnes.",
                "data_ref": "gee://sentinel2/ndvi/claim-550e8400",
                "confidence_weight": 0.85,
                "hash": "a1b2c3d4e5f6...",
            }
        }


class EvidenceSummary(BaseModel):
    """
    Lightweight evidence summary for public transparency views.

    Includes hash for verification but omits full description.
    """
"""
CarbonChain - Evidence & Provenance Models

This module defines the data contracts for the evidence system that underpins
AI MRV verification, authority review, community review, and minting trust.

DESIGN PRINCIPLES:
1. IMMUTABILITY: Once created, evidence records cannot be modified or deleted.
   This ensures auditability and prevents tampering with the verification chain.

2. TRANSPARENCY: Every evidence record includes a SHA256 hash of its immutable
   fields, enabling public verification of data integrity.

3. TRACEABILITY: Evidence records are linked to claims and include source
   attribution, allowing stakeholders to trace the provenance of all data.

4. HASHABILITY: The hash serves as a cryptographic fingerprint that can be
   used to verify evidence integrity without exposing sensitive data.

WHY IMMUTABILITY MATTERS:
- Carbon credit markets require trust in verification data
- Regulators need audit trails that cannot be retroactively altered
- Community oversight depends on transparent, tamper-evident records
- Future blockchain integration requires deterministic hashing
"""

import hashlib
from datetime import datetime
from enum import Enum
from typing import Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, Field, model_validator


class EvidenceType(str, Enum):
    """
    Classification of evidence sources in the verification chain.

    SYSTEM_AI: Automatically generated by AI/ML systems (e.g., satellite MRV)
    USER_UPLOAD: Submitted by claimants (photos, documents)
    DOCUMENT: Official documents, reports, certifications
    COMMUNITY_REPORT: Observations submitted by community reviewers
    """

    SYSTEM_AI = "system_ai"
    USER_UPLOAD = "user_upload"
    DOCUMENT = "document"
    COMMUNITY_REPORT = "community_report"


class EvidenceSource(str, Enum):
    """
    Attribution of who provided the evidence.

    Enables filtering and trust assessment based on source.
    """

    SYSTEM = "system"  # Generated by CarbonChain platform
    AUTHORITY = "authority"  # Submitted by government/regulator
    COMMUNITY = "community"  # Submitted by NGO/public observer
    USER = "user"  # Submitted by claimant


class EvidenceSubmission(BaseModel):
    """
    Input model for creating new evidence.

    Does not include system-generated fields like ID, hash, or timestamp.
    """

    claim_id: UUID = Field(..., description="ID of the claim this evidence supports")
    type: EvidenceType = Field(..., description="Classification of evidence type")
    source: str = Field(
        ...,
        description="Attribution of evidence source (system, authority, community, user)",
    )
    title: str = Field(
        ...,
        min_length=3,
        max_length=200,
        description="Short descriptive title for the evidence",
    )
    description: str = Field(
        ...,
        min_length=10,
        max_length=10000,
        description="Detailed description of what this evidence shows",
    )
    data_ref: str = Field(
        ...,
        max_length=1000,
        description="Reference to evidence data (URL, file path, or logical reference)",
    )
    confidence_weight: float = Field(
        default=0.5,
        ge=0.0,
        le=1.0,
        description=(
            "Trust weight for evidence aggregation (0.0-1.0). "
            "This represents the weight given to this evidence when aggregating multiple evidence sources, "
            "not verification confidence or AI consistency confidence."
        ),
    )


class Evidence(EvidenceSubmission):
    """
    Complete evidence record including system-generated fields.

    IMMUTABILITY CONTRACT:
    Once created, Evidence records MUST NOT be modified or deleted.
    The hash field provides cryptographic proof of data integrity.
    Any attempt to modify evidence should create a new record instead.

    HASH COMPUTATION:
    The hash is a SHA256 digest of the following fields (in order):
    - claim_id
    - type
    - source
    - data_ref
    - created_at (ISO format)

    This hash can be independently verified by any party to ensure
    the evidence has not been tampered with.
    """

    id: UUID = Field(
        default_factory=uuid4, description="Unique identifier for this evidence record"
    )
    hash: str = Field(
        default="",
        description="SHA256 hash of immutable fields for integrity verification",
    )
    created_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="Timestamp when the evidence was recorded (immutable)",
    )

    @model_validator(mode="after")
    def compute_hash(self) -> "Evidence":
        """
        Compute SHA256 hash of immutable fields.

        This hash serves as a cryptographic fingerprint that:
        1. Proves the evidence has not been modified
        2. Enables public verification without exposing raw data
        3. Supports future blockchain anchoring
        """
        if not self.hash:  # Only compute if not already set
            hash_input = (
                f"{self.claim_id}|"
                f"{self.type.value}|"
                f"{self.source}|"
                f"{self.data_ref}|"
                f"{self.created_at.isoformat()}"
            )
            self.hash = hashlib.sha256(hash_input.encode("utf-8")).hexdigest()
        return self

    def verify_hash(self) -> bool:
        """
        Verify that the stored hash matches the computed hash.

        Returns:
            True if hash is valid, False if evidence may have been tampered with.
        """
        hash_input = (
            f"{self.claim_id}|"
            f"{self.type.value}|"
            f"{self.source}|"
            f"{self.data_ref}|"
            f"{self.created_at.isoformat()}"
        )
        expected_hash = hashlib.sha256(hash_input.encode("utf-8")).hexdigest()
        return self.hash == expected_hash

    class Config:
        """Pydantic configuration for the Evidence model."""

        json_schema_extra = {
            "example": {
                "claim_id": "550e8400-e29b-41d4-a716-446655440000",
                "type": "system_ai",
                "source": "system",
                "title": "Satellite-based MRV (Sentinel-2)",
                "description": "NDVI analysis from 2022-01-01 to 2024-12-31. Baseline NDVI: 0.45, Monitoring NDVI: 0.62, Delta: +0.17. Estimated CO₂e: 120-180 tonnes.",
                "data_ref": "gee://sentinel2/ndvi/claim-550e8400",
                "confidence_weight": 0.85,
                "hash": "a1b2c3d4e5f6...",
            }
        }


class EvidenceSummary(BaseModel):
    """
    Lightweight evidence summary for public transparency views.

    Includes hash for verification but omits full description.
    """

    id: UUID
    type: EvidenceType
    source: str
    title: str
    confidence_weight: float
    hash: str
    created_at: datetime
    data_ref: Optional[str] = Field(
        default=None,
        description="Reference to evidence data (file path or URL). No binary content included.",
    )
